services:
  nginx:
    image: nginx:latest
    container_name: server-web
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/blognote
      - ./default.conf:/etc/nginx/conf.d/default.conf
    #depends_on:
     # - php
    links:
      - php-fpm


  php-fpm:
    image: php:8-fpm
    volumes:
      - ./app:/var/www/blognote
