FROM php:8-fpm
#Après installation de php on met à jour les packages et on installe et active mysqli
RUN apt-get update && apt-get upgrade -y

#RUN docker-php-ext-install mysqli pdo_mysql && docker-php-ext-enable mysqli pdo_mysql



